name: Makefile CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup Neovim v0.10.0
      uses: rhysd/action-setup-vim@v1.6.1
      with:
        neovim: true
        version: v0.10.0

    - name: Verify Neovim
      run: nvim --version

    - name: Build project
      run: make

    - name: Run tests
      run: make test
