name: Makefile CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install Neovim
      run: |
        sudo apt-get update
        sudo apt-get install -y neovim

    - name: Verify Neovim
      run: nvim --version

    - name: Build project
      run: make

    - name: Run tests
      run: make test
